// AUTO-GENERATED by scripts/generate-clients.mjs
// Re-run after adding/renaming logos: node scripts/generate-clients.mjs
// Names are derived from the source filenames — adjust the manual
// fields (instagram, name corrections) by editing this file directly;
// the generator preserves nothing across re-runs.

export interface Client {
  logo: string;
  name: string;
  country: string;
  countryCode: string;
  flag: string;
  instagram: string | null;
}

export const clients: Client[] = [
  {
    "logo": "/assets/clientes/argentina/ANTICHE_ARG.webp",
    "name": "Antiche",
    "country": "Argentina",
    "countryCode": "AR",
    "flag": "/assets/banderas/argentina.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/argentina/ATALAYA_ARG.webp",
    "name": "Atalaya",
    "country": "Argentina",
    "countryCode": "AR",
    "flag": "/assets/banderas/argentina.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/argentina/BANCHERO_ARG.webp",
    "name": "Banchero",
    "country": "Argentina",
    "countryCode": "AR",
    "flag": "/assets/banderas/argentina.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/argentina/EL_DESEMBARCO_ARG.webp",
    "name": "El Desembarco",
    "country": "Argentina",
    "countryCode": "AR",
    "flag": "/assets/banderas/argentina.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/argentina/LO_DE_JESUS_ARG.webp",
    "name": "Lo de Jesus",
    "country": "Argentina",
    "countryCode": "AR",
    "flag": "/assets/banderas/argentina.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/argentina/MASSEY_FAMILIA_ARG.webp",
    "name": "Massey Familia",
    "country": "Argentina",
    "countryCode": "AR",
    "flag": "/assets/banderas/argentina.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/argentina/TAVELLI_CHILE.webp",
    "name": "Tavelli",
    "country": "Argentina",
    "countryCode": "AR",
    "flag": "/assets/banderas/argentina.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/argentina/TIENDA_DE_EMPANADAS_ARG.webp",
    "name": "Tienda de Empanadas",
    "country": "Argentina",
    "countryCode": "AR",
    "flag": "/assets/banderas/argentina.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/chile/BARBAZUL_CHILE.webp",
    "name": "Barbazul",
    "country": "Chile",
    "countryCode": "CL",
    "flag": "/assets/banderas/chile.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/chile/KENTO_CHILE.webp",
    "name": "Kento",
    "country": "Chile",
    "countryCode": "CL",
    "flag": "/assets/banderas/chile.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/chile/LA_PICCOLA_ITALIANA_CHILE.webp",
    "name": "La Piccola Italiana",
    "country": "Chile",
    "countryCode": "CL",
    "flag": "/assets/banderas/chile.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/chile/LOCAL_BURGER_CHILE.webp",
    "name": "Local Burger",
    "country": "Chile",
    "countryCode": "CL",
    "flag": "/assets/banderas/chile.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/chile/MALÉVOLO_CHILE.webp",
    "name": "MALÉVOLO",
    "country": "Chile",
    "countryCode": "CL",
    "flag": "/assets/banderas/chile.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/chile/SEVEN_PIZZA_CHILE.webp",
    "name": "Seven Pizza",
    "country": "Chile",
    "countryCode": "CL",
    "flag": "/assets/banderas/chile.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/chile/TAVELLI_CHILE.webp",
    "name": "Tavelli",
    "country": "Chile",
    "countryCode": "CL",
    "flag": "/assets/banderas/chile.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/colombia/EHOMAKI_COLOMBIA.webp",
    "name": "Ehomaki",
    "country": "Colombia",
    "countryCode": "CO",
    "flag": "/assets/banderas/colombia.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/colombia/GRATIN_BURGER_COLOMBIA.webp",
    "name": "Gratin Burger",
    "country": "Colombia",
    "countryCode": "CO",
    "flag": "/assets/banderas/colombia.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/colombia/PRIME_COLOMBIA.webp",
    "name": "Prime",
    "country": "Colombia",
    "countryCode": "CO",
    "flag": "/assets/banderas/colombia.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/colombia/SAGRADA_TAQUERIA_COLOMBIA.webp",
    "name": "Sagrada Taqueria",
    "country": "Colombia",
    "countryCode": "CO",
    "flag": "/assets/banderas/colombia.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/colombia/SUSHIMAN_COLOMBIA.webp",
    "name": "Sushiman",
    "country": "Colombia",
    "countryCode": "CO",
    "flag": "/assets/banderas/colombia.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/colombia/TIRANO_BURGER_REX_COLOMBIA.webp",
    "name": "Tirano Burger Rex",
    "country": "Colombia",
    "countryCode": "CO",
    "flag": "/assets/banderas/colombia.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/ALMIBAR_ESPAÑA.webp",
    "name": "Almibar",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/BISTEC_ESPAÑA.webp",
    "name": "Bistec",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/DELICATESSEN_ARGENTINA_ESPAÑA.webp",
    "name": "Delicatessen Argentina",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/EMPANADA_CLUB_ESPAÑA.webp",
    "name": "Empanada Club",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/FILO_SANDWICHERÍA_ESPAÑA.webp",
    "name": "Filo SANDWICHERÍA",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/FUNDIDO_ESPAÑA.webp",
    "name": "Fundido",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/GROSSO_NAPOLETANO_ESPAÑA.webp",
    "name": "Grosso Napoletano",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/GRUPO_BARBILLÓN_ESPAÑA.webp",
    "name": "Grupo BARBILLÓN",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/HACIENDA_ALAKRAN_ESPAÑA.webp",
    "name": "Hacienda Alakran",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/LA_BIRRA_BAR_ESPAÑA.webp",
    "name": "La Birra Bar",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/LA_BOMBONERA_GROUP_ESPAÑA.webp",
    "name": "La Bombonera Group",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/LOCCO_BURGER_ESPAÑA.webp",
    "name": "Locco Burger",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/MALVÓN_EMPANADAS_ESPAÑA.webp",
    "name": "MALVÓN Empanadas",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/MISTER_NOODLES_ESPAÑA.webp",
    "name": "Mister Noodles",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/MOLI_TAPAS_ESPAÑA.webp",
    "name": "Moli Tapas",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/MUDRÁ_PLANT_BASED_ESPAÑA.webp",
    "name": "MUDRÁ Plant Based",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/NICKEL_ESPAÑA.webp",
    "name": "Nickel",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/PINSA_PIZZA_ESPAÑA.webp",
    "name": "Pinsa Pizza",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/SAO_MEDIALUNAS_ESPAÑA.webp",
    "name": "Sao Medialunas",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/STREET_FOOD_BURGER_ESPAÑA.webp",
    "name": "Street Food Burger",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/españa/ZANA_PASTA_ESPAÑA.webp",
    "name": "Zana Pasta",
    "country": "España",
    "countryCode": "ES",
    "flag": "/assets/banderas/espana.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/BALDORIA_MEXICO.webp",
    "name": "Baldoria",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/BARRIO_CHICKEN_MEXICO.webp",
    "name": "Barrio Chicken",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/BIG_SLICE_MEXICO.webp",
    "name": "Big Slice",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/BOSTON_MEXICO.webp",
    "name": "Boston",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/DOGGIS_MEXICO.webp",
    "name": "Doggis",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/EL_DIEZ_MEXICO.webp",
    "name": "El Diez",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/GREEN_PIZZA_MEXICO.webp",
    "name": "Green Pizza",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/MOMENTITO_MEXICO.webp",
    "name": "Momentito",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/SHINTAI_MEXICO.webp",
    "name": "Shintai",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/TAQUEARTE_MEXICO.webp",
    "name": "Taquearte",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/mexico/TOMMY_BEANS_MEXICO.webp",
    "name": "Tommy Beans",
    "country": "México",
    "countryCode": "MX",
    "flag": "/assets/banderas/mexico.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/peru/BLACK_POKE_PERÚ.webp",
    "name": "Black Poke",
    "country": "Perú",
    "countryCode": "PE",
    "flag": "/assets/banderas/peru.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/peru/COQUI_CASTILLO_PERÚ.webp",
    "name": "Coqui Castillo",
    "country": "Perú",
    "countryCode": "PE",
    "flag": "/assets/banderas/peru.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/peru/EL_CEDRO_CAFÉ_PERÚ.webp",
    "name": "El Cedro CAFÉ",
    "country": "Perú",
    "countryCode": "PE",
    "flag": "/assets/banderas/peru.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/peru/EL_FOGÓN_DEL_ASADOR_PERÚ.webp",
    "name": "El FOGÓN del Asador",
    "country": "Perú",
    "countryCode": "PE",
    "flag": "/assets/banderas/peru.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/peru/HAVANNA_PERÚ.webp",
    "name": "Havanna",
    "country": "Perú",
    "countryCode": "PE",
    "flag": "/assets/banderas/peru.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/peru/KAUZA_PERÚ.webp",
    "name": "Kauza",
    "country": "Perú",
    "countryCode": "PE",
    "flag": "/assets/banderas/peru.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/peru/SAM`S_CHICKEN_PERÚ.webp",
    "name": "SAM`S Chicken",
    "country": "Perú",
    "countryCode": "PE",
    "flag": "/assets/banderas/peru.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/peru/SUNCHI_PERÚ.webp",
    "name": "Sunchi",
    "country": "Perú",
    "countryCode": "PE",
    "flag": "/assets/banderas/peru.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/uruguay/FREDDO_URUGUAY.webp",
    "name": "Freddo",
    "country": "Uruguay",
    "countryCode": "UY",
    "flag": "/assets/banderas/uruguay.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/usa/BAIRES_GRILL_USA.webp",
    "name": "Baires Grill",
    "country": "Estados Unidos",
    "countryCode": "US",
    "flag": "/assets/banderas/usa.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/usa/BANCHERO_MIAMI_USA.webp",
    "name": "Banchero Miami",
    "country": "Estados Unidos",
    "countryCode": "US",
    "flag": "/assets/banderas/usa.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/usa/EL_CLUB_DE_LA_MILANESA_USA.webp",
    "name": "El Club de la Milanesa",
    "country": "Estados Unidos",
    "countryCode": "US",
    "flag": "/assets/banderas/usa.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/usa/LA_BIRRA_BAR_USA.webp",
    "name": "La Birra Bar",
    "country": "Estados Unidos",
    "countryCode": "US",
    "flag": "/assets/banderas/usa.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/usa/NOVECENTO_USA.webp",
    "name": "Novecento",
    "country": "Estados Unidos",
    "countryCode": "US",
    "flag": "/assets/banderas/usa.svg",
    "instagram": null
  },
  {
    "logo": "/assets/clientes/usa/V&E_HOSPITALITY_USA.webp",
    "name": "V&E Hospitality",
    "country": "Estados Unidos",
    "countryCode": "US",
    "flag": "/assets/banderas/usa.svg",
    "instagram": null
  }
];
