// Reads public/assets/clientes/<country>/*.webp and writes a typed
// clients array to data/clients.ts. Re-run any time Luli adds or
// renames client logos:
//
//     node scripts/generate-clients.mjs

import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT_DIR = "public/assets/clientes";
const OUT_FILE = "data/clients.ts";

/** folderName -> { code (ISO 3166-1 alpha-2), display name, flag basename } */
const COUNTRY_MAP = {
  argentina: { code: "AR", display: "Argentina", flag: "argentina" },
  chile: { code: "CL", display: "Chile", flag: "chile" },
  colombia: { code: "CO", display: "Colombia", flag: "colombia" },
  españa: { code: "ES", display: "España", flag: "espana" },
  mexico: { code: "MX", display: "México", flag: "mexico" },
  peru: { code: "PE", display: "Perú", flag: "peru" },
  uruguay: { code: "UY", display: "Uruguay", flag: "uruguay" },
  usa: { code: "US", display: "Estados Unidos", flag: "usa" },
};

// Country suffix tokens stripped from filenames before deriving the display name.
const SUFFIX_RE =
  /_(?:ARG|ARGENTINA|CHL|CHILE|COL|COLOMBIA|ESP|ESPAÑA|ESPANA|MEX|MEXICO|MX|PER|PERU|PERÚ|URU|URUGUAY|USA)$/i;

// Small Spanish words kept lowercase when they're not the first word.
const SMALL_WORDS = new Set([
  "de",
  "del",
  "la",
  "las",
  "el",
  "los",
  "y",
  "e",
  "en",
  "al",
]);

function deriveName(filename) {
  const base = filename.replace(/\.webp$/i, "");
  const stripped = base.replace(SUFFIX_RE, "");
  return stripped
    .split(/[_\s]+/)
    .filter(Boolean)
    .map((word, i) => {
      const lower = word.toLowerCase();
      if (i > 0 && SMALL_WORDS.has(lower)) return lower;
      // preserve all-caps tokens that aren't just one letter (acronyms)
      if (word.length >= 2 && word === word.toUpperCase() && /[A-Z]/.test(word)) {
        // single-cap words get title-cased; multi-cap stays (e.g. "V&E")
        if (/[^A-Z]/.test(word)) return word;
      }
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join(" ");
}

const clients = [];
for (const [folder, info] of Object.entries(COUNTRY_MAP)) {
  const dir = join(ROOT_DIR, folder);
  if (!existsSync(dir)) {
    console.warn(`Skipping missing folder: ${dir}`);
    continue;
  }
  const files = readdirSync(dir)
    .filter((f) => f.toLowerCase().endsWith(".webp"))
    .sort();
  for (const file of files) {
    clients.push({
      logo: `/assets/clientes/${folder}/${file}`,
      name: deriveName(file),
      country: info.display,
      countryCode: info.code,
      flag: `/assets/banderas/${info.flag}.svg`,
      instagram: null,
    });
  }
}

const banner = `// AUTO-GENERATED by scripts/generate-clients.mjs
// Re-run after adding/renaming logos: node scripts/generate-clients.mjs
// Names are derived from the source filenames — adjust the manual
// fields (instagram, name corrections) by editing this file directly;
// the generator preserves nothing across re-runs.
`;

const types = `
export interface Client {
  logo: string;
  name: string;
  country: string;
  countryCode: string;
  flag: string;
  instagram: string | null;
}
`;

const body = `\nexport const clients: Client[] = ${JSON.stringify(clients, null, 2)};\n`;

writeFileSync(OUT_FILE, banner + types + body);
console.log(`Wrote ${OUT_FILE} — ${clients.length} clients across ${Object.keys(COUNTRY_MAP).length} countries.`);
